# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassianlabs/docker-node-jdk-chrome-firefox

clone:
  depth: 20

definitions:
  caches:
    sonar: /root/.sonar/cache
    nodemodules: node_modules

pipelines:
  pull-requests:
    dev:
      - step:
          caches:
            - sonar
          script:
            - apt-get update && apt-get install -y unzip nodejs
            - npm install typescript
            - curl --insecure -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
            - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
            - ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.projectKey=152tech_centreel-frontend -Dsonar.organization=152tech -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

  branches:
    dev:
      - step:
          name: Deploy to Dev
          deployment: test
          caches:
            - nodemodules
          script:
            - apt-get update && apt-get install -qyf openssh-client
            - npm install
            - npm install -g @angular/cli
            - ng build --configuration=dev
            - scp -r dist/* root@169.48.27.167:/s3/dev-frontend

    testing:
      - step:
          name: Deploy to testing
          deployment: test
          caches:
            - nodemodules
          script:
            - apt-get update && apt-get install -qyf openssh-client
            - npm install
            - npm install -g @angular/cli
            - ng build --configuration=testing
            - scp -o "ProxyCommand ssh root@169.48.27.167 -W %h:%p" -o StrictHostKeyChecking='no' -r dist/* root@10.166.99.29:/var/www/html/

    master:
      - step:
          name: Deploy to Production
          deployment: production
          caches:
            - nodemodules
          script:
            - apt-get update && apt-get install -qyf openssh-client
            - npm install
            - npm install -g @angular/cli
            #- ng build --prod --deploy-url https://s3.ca-central-1.amazonaws.com/centreel-production-frontend/
            - ng build --prod
            - scp -o "ProxyCommand ssh ubuntu@ec2-35-182-71-226.ca-central-1.compute.amazonaws.com -W %h:%p" -o StrictHostKeyChecking='no' -r dist/* ubuntu@10.0.130.78:/var/www/html/
            #- scp -r dist/* ubuntu@ec2-35-182-71-226.ca-central-1.compute.amazonaws.com:/home/ubuntu/s3/centreel-production-frontend
