name: centreel

on:
  push:
    branches: [main, dev, test]
     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}
      - name: Build Application
        run: npm install && npm run build 
      - name: Deploy app build to S3 bucket to prodution
        if: endsWith(github.ref, '/main')
        run: aws s3 sync ./dist/ s3://centreel-production-frontend --delete
      - name: Deploy app build to S3 bucket to testing
        if: endsWith(github.ref, '/test')
        run: aws s3 sync ./dist/ s3://centreel-testing-frontend --delete
      - name: Deploy app build to S3 bucket to dev
        if: endsWith(github.ref, '/dev')
        run: aws s3 sync ./dist/ s3://centreel-dev-frontend --delete
      - name: Create CloudFront Cache Invalidation
        uses: chetan/invalidate-cloudfront-action@master
        if: endsWith(github.ref, '/main')
        env:
          DISTRIBUTION: ${{ secrets.AWS_CF_DISTRIBUTION_ID_PROD }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY
        if: endsWith(github.ref, '/test')
        env:
          DISTRIBUTION: ${{ secrets.AWS_CF_DISTRIBUTION_ID_TEST }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY
        if: endsWith(github.ref, '/dev')
        env:
          DISTRIBUTION: ${{ secrets.AWS_CF_DISTRIBUTION_ID_TEST }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY